### ISSUE TITLE
Hazelcast client discovery

### ISSUE THREAD

**Issue by dannygu** [commercehub-oss/hazelcast-discovery-amazon-ecs#2]
Hi,

First of thanks for this project.

I've been wondering what are you doing in terms of discovery for your hazelcast clients ? i need our clients to discover our hazelcast servers dynamically as well.

Thanks!

**Comment by mhurne** [comment]
Unfortunately, I do not have experience using a client/server Hazelcast topology. Instead, we embed it directly in our applications. I suspect that some enhancements would be needed to support client discovery of the cluster in a client/server deployment. If you would like to make those enhancements and create a pull request, I would be happy to review it!

**Comment by mhurne** [comment]
As this project is now deprecated, CommerceHub will not be contributing further on this ticket.  Please feel free to work on it further yourself under the terms of the project license if desired.
